### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by vladimirbobenic** [arufahc/negicc#1]
Hello,

after installing all dependencies I got this error:

build_prof.py: error: unrecognized arguments: /
make: *** [sony_a7rm4_portra400_0] Error 2

tested on Osx Catalina and Centos 7

Am I doing something wrong?:)

Thank you

Vladimir

**Comment by arufahc** [comment]
Hey,

Try removing '$(INSTALL_DIR)/'  from line 194. Or just run the command in
Makefile "python3 build_prof.py --src=data/portra400-0-cs100a_train.txt
--white_x=0.3353 --white_y=0.3496 --film_name="Sony A7RM4 Portra400"
--fit_intercept=1 --debug" in command line and see happens.

**Comment by arufahc** [comment]
I removed the stray '/' character in Makefile, you can sync and try again.

**Comment by vladimirbobenic** [comment]
thank you!

but after executing again 

I got error 1:)

Step 3: Build 3D LUT from positive RGB to measured XYZ.
Traceback (most recent call last):
  File "build_prof.py", line 548, in <module>
    main()
  File "build_prof.py", line 475, in main
    test_white_XYZ = run_chromatic_adaptation_on_ref_XYZ()
  File "build_prof.py", line 345, in run_chromatic_adaptation_on_ref_XYZ
    test_white_XYZ = np.array(colour.xyY_to_XYZ(
AttributeError: module 'colour' has no attribute 'xyY_to_XYZ'
make: *** [sony_a7rm4_portra400_0] Error 1

**Comment by arufahc** [comment]
You need the colour-science package. Try pip install colour-science.

**Comment by arufahc** [comment]
I added install commands in the README.md, try to use it to install the
python packages with pip.
